Datetime filter update
logzio/logzio-azure-blob-trigger pull request #6
Opened 2021-11-08 08:08 UTC by ShiranAvidov

Change datetime filter parameters and adding parameter (DatetimeFormat)
Add text datetime filter
Change logzio_shipper to use threads and queues
Fix slowness when using datetime filter
Add logs
Fix tests (using requests-mock)

2021-11-08 17:56 UTC, Doron-Bargo requested changes
lgtm
just make the Readme more clear

2021-11-08 17:56 UTC, Doron-Bargo commented on README.md
> +| Datetime Format | The datetime format of DatetimeFilter and datetime field in each log (for example: %Y/%m/%dT%H:%M:%S%z is for 2021/11/01T10:10:10+0000 datetime). If the format is wrong, the log w
Can you rearrange it so all the required parameters will be at the beginning and the non-required will be at the end?

2021-11-08 17:56 UTC, Doron-Bargo commented on README.md
> +| Datetime Filter | Every log with datetime greater or equal to this datetime will be shipped to Logz.io (for it to take effect DatetimeFinder and DatetimeFormat must not be empty). Leave empty if yo
Need example what is the Datetime structure

2021-11-09 08:11 UTC, ShiranAvidov commented on README.md
> +| Datetime Format | The datetime format of DatetimeFilter and datetime field in each log (for example: %Y/%m/%dT%H:%M:%S%z is for 2021/11/01T10:10:10+0000 datetime). If the format is wrong, the log w
done

2021-11-09 08:12 UTC, ShiranAvidov commented on README.md
> +| Datetime Filter | Every log with datetime greater or equal to this datetime will be shipped to Logz.io (for it to take effect DatetimeFinder and DatetimeFormat must not be empty). Leave empty if yo
done

2021-11-09 08:45 UTC, Doron-Bargo approved these changes
Great work

2021-11-09 09:00 UTC, merged